AWSTemplateFormatVersion: 2010-09-09
Description: Deploy a VPC with other networking resources, a Private DNS Zone and an ECS Repo
Parameters: 
  DomainName:
    Type: String
    Default: simple-wordcount.com

Resources: 
  VPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsHostnames: true
        Tags:
        - Key: Name
          Value: simple-wordcount VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: simple-wordcount Internet Gateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: !Select 
        - '0'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: Public Subnet 1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select 
        - '1'
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: Public Subnet 2

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Public Route Table

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable


  RootDomain:
    Type: AWS::Route53::HostedZone
    DependsOn: VPC
    Properties:
        HostedZoneConfig: 
          Comment: 'My hosted zone for ${DomainName} service'
        Name: !Ref DomainName
        VPCs: 
          - 
            VPCId: !Ref VPC
            VPCRegion: !Ref "AWS::Region"


  ECSRepository:
     Type: AWS::ECR::Repository
     Properties:
         RepositoryName: "simple-wordcount-api"


Outputs:
  VPC:
    Description: VPC
    Value: !Ref VPC

  Subnet1ID:
    Description: Subnet 1
    Value: !Ref PublicSubnet1

  Subnet2ID:
    Description: Subnet 2
    Value: !Ref PublicSubnet2


  REPO:
    Description: ECR Repository
    Value: !GetAtt 
       - ECSRepository
       - RepositoryUri

